### ISSUE TITLE
a way to set the page title

### ISSUE THREAD

**Issue by nayshice** [electric-cloud/Unplug#1]
Right now, the page title always shows up as "unplug 2.0.2", and I can't insert a `<title>` element into the XHTML to change it.  It would be awesome if there was a hook to change that.

![image](https://cloud.githubusercontent.com/assets/1359970/6422596/8c599384-be8f-11e4-89e4-c392449e8d1f.png)

**Comment by nayshice** [comment]
@ctron00 sent me a cool way to get this to work: `<script>document.title = "My Title";</script>` -- it shows "unplug 2.0.2" until the page is loaded, but then it switches to the user-defined title.  @mjwesterhof I'll let you decide whether you want to document that, or add something to unplug to do that natively.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/Unplug#1
